export const READER_NOT_CONNECTED = 'READER_NOT_CONNECTED';
export const INVALID_RESPONSE = 'INVALID_RESPONSE';
export const EMPTY_RESPONSE = 'EMPTY_RESPONSE';
export const READER_ERROR = 'READER_ERROR';
export const INVALID_FORMAT = 'INVALID_FORMAT'