export declare const READER_NOT_CONNECTED = "READER_NOT_CONNECTED";
export declare const READER_ALREADY_CONNECTED = "READER_ALREADY_CONNECTED";
export declare const INVALID_RESPONSE = "INVALID_RESPONSE";
export declare const EMPTY_RESPONSE = "EMPTY_RESPONSE";
export declare const READER_ERROR = "READER_ERROR";
export declare const SOCKET_ERROR = "SOCKET_ERROR";
export declare const INVALID_FORMAT = "INVALID_FORMAT";
export declare const NOT_SUPPORTED_OPERATION = "NOT_SUPPORTED_OPERATION";
